	import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		
		int repeat = Integer.parseInt(args[0]);
		double average = 0.0;
		int famOfTwo = 0;
		int famOfThree = 0;
		int famOfFour = 0;
		
		for (int i=0; i<repeat; i++){
		int amountOfChilds = 0;
		boolean boy = true;
		boolean notSame = true;
		
		double gen1 = Math.random();
			if (gen1 > 0.5){	
				amountOfChilds++;
				while(notSame){
					double gen2 = Math.random();
					if (gen2 > 0.5){
						amountOfChilds++;
					}
					else{
						amountOfChilds++;
						notSame = false;
					}
				}
			}
			else {
				amountOfChilds++;
				while(notSame){
					double gen2 = Math.random();
					if (gen2 < 0.5){
						amountOfChilds++;
					}
					else{
						amountOfChilds++;
						notSame = false;
					}
				}
			}

			average += amountOfChilds;
			
			switch(amountOfChilds){
				case 2:
				famOfTwo++;
				break;
				case 3:
				famOfThree++;
				break;
				case 4:
				famOfFour++;
				break;
				default:
				famOfFour++;
			}	
	}
	
		System.out.println("Average: " + average/repeat + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+famOfTwo);
		System.out.println("Number of families with 3 children: "+famOfThree);
		System.out.println("Number of families with 4 or more children: "+famOfFour);
		
		if (famOfTwo >= famOfThree && famOfTwo >= famOfFour)
			System.out.println("The most common number of children is 2.");
		else if(famOfThree >= famOfFour)
			System.out.println("The most common number of children is 3.");
		else
			System.out.println("The most common number of children is 4 or more.");
		    
	}
}
